---
logstash_user:  logstash
logstash_group: "{{ logstash_user }}"

logstash_log_dir:     /var/log/logstash
logstash_home_dir:    /var/lib/logstash
logstash_conf_dir:    /etc/logstash/conf.d
logstash_install_dir: /opt/logstash
logstash_pid_dir:     /var/run

####################
##  Default Settings
logstash_javacmd: /usr/bin/java
logstash_opts:      []                # e.g. [ "--debug" ]
logstash_java_opts: []
logstash_heap_size: "1g" 
logstash_nice:       19
logstash_open_files: 16384
logstash_use_gc_logging: false
logstash_kill_on_stop_timeout: 0

############
##  Package
logstash_version: 2.2
logstash_signing_key_url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
logstash_apt_repo: "deb http://packages.elastic.co/logstash/{{ logstash_version }}/debian stable main"

###########
##  Config
logstash_input_configs: 
  - |
    file { 
            path => ["/var/log/boot.log"]
       }
logstash_filter_configs: []
logstash_output_configs: 
  - |
    stdout { 
            codec => rubydebug
        }
  - |
    elasticsearch { 
            hosts => ["localhost:9200"] 
        }
