---
galaxy_info:
  author: "Ogonna Iwunze"
  company: EqualExperts
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
  galaxy_tags:
    - elk
    - logstash
dependencies: []
  
