---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  ansible_verbose: false
  ansible_verbosity: 2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
