---
# defaults file for ansible-role-kibana-4
kibana_server_name: osckibana
kibana_nginx_access_log: /var/log/nginx/kibana-4.access.log
kibana_version: 4.5

kibana_username: kibana
kibana_password: password

kibana_server_port: 5601
kibana_server_host: "{{kibana_server_host}}"
