---
# Debian-specific vars file for elasticsearch

elasticsearch_repository:
  url: https://packages.elastic.co/elasticsearch/2.x/debian
  type: stable main

elasticsearch_packages:
  - elasticsearch
# Requires Backported version of rsyslog
# - rsyslog-elasticsearch

elasticsearch_config:
  master: /etc/elasticsearch/elasticsearch.yml
  logging: /etc/elasticsearch/logging.yml
  owner: root
  data: elasticsearch
  group: elasticsearch

elasticsearch_service: elasticsearch

elasticsearch_default_data_dir: /var/lib/elasticsearch/data
