---
galaxy_info:
  author: Jonathan Wright <jon@than.io>
  description: Install and configure ElasticSearch, with test-kitchen/serverspec tests.
  issue_tracker_url: https://github.com/jonathanio/ansible-role-elasticsearch/issues
  github_branch: master
  license: BSD
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - wheezy
  galaxy_tags:
    - system
    - elasticsearch
    - elastic
    - elk
    - test-kitchen

dependencies: []
