---
# tasks file for cdnfront-openresty-conf
- name: copy conf
  template: src="nginx_server.conf.j2" dest="/usr/local/nginx/nginx/conf/servers/{{nginx_server_conf}}" owner=root group=root mode=0755
  tags:
    - nginx-conf
  notify: restart nginx
