---
# Debain-specific package tasks for elasticsearch

- include_vars: debian.yml

- name: Install HTTPS driver for APT
  apt:
    name: apt-transport-https
    state: installed

- name: Install ElasticSearch repository
  apt_repository:
    repo: "deb {{ elasticsearch_repository.url }} {{ elasticsearch_repository.type }}"
    filename: elasticsearch
    state: present
    
- apt: update_cache=yes cache_valid_time=72000  autoremove=yes upgrade=safe
  ignore_errors: yes

- name: Install ElasticSearch
  apt:
    name: "{{ item }}"
    allow_unauthenticated: yes
    state: installed
  with_items:
    "{{ elasticsearch_packages }}"

- name: Configure ElasticSearch Defaults
  template:
    src: elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: 0644
  notify:
    restart elasticsearch
