---
# firewall-specific tasks for elasticsearch

- name: Open firewalld ports for ElasticSearch
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
    - "{{ elasticsearch_port_http }}"
    - "{{ elasticsearch_port_transport }}"
  when:
    (use_firewalld is defined and use_firewalld)

- name: Open ufw ports for ElasticSearch
  ufw:
    port: "{{ item }}"
    proto: tcp
    direction: in
    policy: allow
  with_items:
    - "{{ elasticsearch_port_http }}"
    - "{{ elasticsearch_port_transport }}"
  when:
    (use_ufw is defined and use_ufw)
