---
# tasks file for elasticsearch

- include: debian.yml
  when:
    ansible_os_family == "Debian"
- include: redhat.yml
  when:
    ansible_os_family == "RedHat"
- include: arch.yml
  when:
    ansible_os_family == "Archlinux"

- include: config.yml
- include: firewall.yml
- include: service.yml
- include: plugins.yml
