---
# 安装openresty，不作配置
- name: install prepare software
  apt: name="{{item}}" state=present
  sudo: true
  with_items:
    - "libreadline-dev"
    - "libpcre3-dev"
    - "libssl-dev"
    - "perl"
    - "build-essential"


- stat: path="/usr/local/openresty"
  register: openresty

- name: download openresty
  get_url: url="{{openresty_download_url}}" dest="/tmp" owner={{ user }} group={{ user_group }}
  when: openresty.stat.exists == False
  tags:
    - install

- name: install nginx
  unarchive: src="/tmp/{{openresty_version}}.tar.gz" dest="/tmp" mode="go-w" copy=no
  when: openresty.stat.exists == False

- shell: "cd /tmp/{{openresty_version}}/ && sudo ./configure --with-luajit  "
  when: openresty.stat.exists == False

- shell: "cd /tmp/{{openresty_version}}/  && make && sudo make install"
  when: openresty.stat.exists == False


- file: src="/usr/local/openresty" dest="/usr/local/nginx" owner=root group=root state=link

- template: src="nginx.conf" force=true dest="/usr/local/openresty/nginx/conf/" owner=root group=root

- name: mkdir log folder
  file: path="{{nginx_log_path}}" owner=nobody group=root state=directory mode=0755

- name: copy nginx init.d script
  copy: src="nginx" dest="/etc/init.d" force=true
- file: dest="/etc/init.d/nginx" state=touch mode="u=rwx,g=rx,o=rx" force=true owner=root group=root
- shell: "sudo update-rc.d -f nginx defaults"

- name: mkdir serviers dir
  file: path="/usr/local/nginx/nginx/conf/servers" state=directory owner=root group=root recurse=true

- name: cut log
  file: path="{{nginx_log_cut_path}}" owner=nobody group=root state=directory mode=0755

- name: template log cut sh
  template: src="log_cut.sh" dest="/var/run" owner={{user}} group={{user_group}} mode=0766 force=true

- name: cron execute log cut
  cron: name="nginx log cut" minute="00" hour="00" day="*" month="*" job="sh /var/run/log_cut.sh" user=root

- service: name="nginx" state="restarted" enabled=yes
